[build]
  base = "."
  publish = "build/"
  command = "yarn install && yarn run prod"
#  functions = "project/functions/" // TODO: LAMBDA FUNCTIONS

  [build.processing]
    skip_processing = false
  [build.processing.css]
    bundle = true
    minify = true
  [build.processing.js]
    bundle = true
    minify = true
  [build.processing.html]
    pretty_urls = true
  [build.processing.images]
    compress = true

 [headers]
# Define which paths this specific [[headers]] block will cover.
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
